[package]
name = "wobookd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
wobook-core.workspace = true
automerge-repo.workspace = true
wobook-sync.workspace = true
async-trait.workspace = true
automerge.workspace = true
anyhow.workspace = true
clap.workspace = true
fs2.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
