[package]
name = "wobook-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
automerge-repo.workspace = true
async-trait.workspace = true
automerge.workspace = true
bytes.workspace = true
encoding_rs.workspace = true
nucleo-matcher.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
scraper.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true
