plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

// Rust: wobook-ffi built with cargo-ndk, Kotlin bindings generated by the
// crate's own uniffi-bindgen. Nothing generated is committed.
val repoRoot: File = rootProject.projectDir.parentFile
val rustProfile: String = (findProperty("wobook.rustProfile") as String?) ?: "release"
val rustAbis = listOf("arm64-v8a" to "aarch64-linux-android", "x86_64" to "x86_64-linux-android")
val jniOut = layout.buildDirectory.dir("generated/jniLibs")
val bindingsOut = layout.buildDirectory.dir("generated/uniffi")

val cargoNdkBuild by tasks.registering(Exec::class) {
    group = "rust"
    description = "Builds libwobook_ffi.so for ${rustAbis.joinToString { it.first }}"
    workingDir = repoRoot
    val args = mutableListOf("cargo", "ndk")
    rustAbis.forEach { (abi, _) -> args += listOf("-t", abi) }
    args += listOf("-P", "31", "-o", jniOut.get().asFile.absolutePath, "build", "-p", "wobook-ffi", "--lib")
    if (rustProfile == "release") args += "--release"
    commandLine(args)
    inputs.files(fileTree(repoRoot.resolve("crates")) { include("**/*.rs", "**/Cargo.toml", "**/uniffi.toml") })
    inputs.file(repoRoot.resolve("Cargo.lock"))
    outputs.dir(jniOut)
}

val uniffiBindgen by tasks.registering(Exec::class) {
    group = "rust"
    description = "Generates Kotlin bindings for wobook-ffi"
    dependsOn(cargoNdkBuild)
    workingDir = repoRoot
    val library = repoRoot.resolve("target/${rustAbis.last().second}/$rustProfile/libwobook_ffi.so")
    commandLine(
        "cargo", "run", "--quiet", "-p", "wobook-ffi", "--bin", "uniffi-bindgen", "--",
        "generate", "--library", library.absolutePath, "--language", "kotlin",
        "--out-dir", bindingsOut.get().asFile.absolutePath, "--no-format",
    )
    inputs.file(library)
    outputs.dir(bindingsOut)
}

android {
    namespace = "dev.wochap.wobook"
    compileSdk = 36
    buildToolsVersion = "36.0.0"

    defaultConfig {
        applicationId = "dev.wochap.wobook"
        minSdk = 31
        targetSdk = 36
        versionCode = 1
        versionName = "0.1.0"
        ndk { abiFilters += listOf("arm64-v8a", "x86_64") }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            // Sideloaded personal build: sign release with the debug key.
            signingConfig = signingConfigs.getByName("debug")
        }
    }

    sourceSets {
        getByName("main") {
            jniLibs.srcDir(jniOut)
            java.srcDir(bindingsOut)
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    packaging {
        jniLibs.useLegacyPackaging = false
    }

    lint {
        abortOnError = false
        disable += setOf("GradleDependency", "NewerVersionAvailable", "AndroidGradlePluginVersion")
    }
}

kotlin {
    jvmToolchain(21)
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
}

tasks.named("preBuild") { dependsOn(uniffiBindgen) }

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.process)
    implementation(libs.androidx.navigation.compose)
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.datastore.preferences)
    implementation(libs.work.runtime.ktx)
    implementation(libs.camerax.camera2)
    implementation(libs.camerax.lifecycle)
    implementation(libs.camerax.view)
    implementation(libs.zxing.cpp)
    implementation(libs.zxing.core)
    implementation("${libs.jna.get()}@aar")
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.phosphor.icon)
    debugImplementation(libs.compose.ui.tooling)

    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.serialization.json)
}
